name: project-functional
version: 0.1.0.0
github: "def4alt/project-functional"
license: MIT
author: "Andrii Olkhovych"
maintainer: "bronzemonet@gmail.com"
copyright: "2020 Andrii Olkhovych"

extra-source-files:
- README.md
- ChangeLog.md

description: Please see the README on GitHub at <https://github.com/def4alt/project-functional#readme>

dependencies:
- base

library:
  source-dirs: src

executables:
  project-functional-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - project-functional

tests:
  project-functional-test:
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    source-dirs: test
    dependencies:
    - project-functional
    - hspec
